version: "3.8"

x-app-defaults: &app-defaults
  restart: always
  networks:
    - apinaio
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  ollama-api: #From https://github.com/jmorganca/ollama
    <<: *app-defaults
    container_name: ollama-api
    image: ollama/ollama:latest
    volumes:
      - ./workspace/ollama:/app
      - ./workspace/ollama/models:/root/.ollama/models
      - ./config/ollama/entrypoint.sh:/app/entrypoint.sh
      - ./config/ollama/modelfiles:/app/modelfiles
    ports:
      - ${OLLAMA_PORT_HOST:-11434}:${OLLAMA_PORT:-11434}
    entrypoint: /app/entrypoint.sh

  comfyui-api: #From https://github.com/ai-dock/comfyui
    <<: *app-defaults
    container_name: comfyui-api
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    volumes:
      - ./workspace:${WORKSPACE:-/workspace/}:rshared
      - ./config/comfyui/provisioning.sh:/opt/ai-dock/bin/provisioning.sh
      - ./config/comfyui/models.csv:/opt/ai-dock/bin/models.csv
      - ./config/comfyui/nodes.csv:/opt/ai-dock/bin/nodes.csv
    ports:
      - ${COMFYUI_PORT_HOST:-8188}:${COMFYUI_PORT:-8188}
    environment:
      - COMFYUI_BRANCH=${COMFYUI_BRANCH:-master}
      - COMFYUI_FLAGS=${COMFYUI_FLAGS:-}
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
      - WORKSPACE=${WORKSPACE:-/workspace}
      - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH}
      - WEB_USER=${WEB_USER}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}
      - NODES_CSV_FILE=${NODES_CSV_FILE:-/opt/ai-dock/bin/nodes.csv}
      - MODELS_CSV_FILE=${MODELS_CSV_FILE:-/opt/ai-dock/bin/models.csv}

  ffmpeg-api: #From https://github.com/jaideep2/ffmpeg-api/
    <<: *app-defaults
    container_name: ffmpeg-api
    image: ghcr.io/jaideep2/ffmpeg-api:latest
    volumes:
      - ./workspace/ffmpeg/cache:/tmp
    ports:
      - ${FFMPEG_PORT_HOST:-3000}:${FFMPEG_PORT:-3000}
    environment:
        - KEEP_ALL_FILES=${KEEP_ALL_FILES:-false}
        - LOG_LEVEL=${LOG_LEVEL:-info}

networks:
  apinaio:
    name: apinaio
    driver: bridge