version: "3.8"

x-app-defaults: &app-defaults
  restart: always
  networks:
    - apinaio
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, video] # https://stackoverflow.com/a/75809584

services:
  ollama-api:
    <<: *app-defaults
    container_name: ollama-api
    image: ollama/ollama:latest
    volumes:
      - ./workspace/ollama:/app
      - ./workspace/ollama/models:/root/.ollama/models
      - ./config/ollama/entrypoint.sh:/app/entrypoint.sh
      - ./config/ollama/modelfiles:/app/modelfiles
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
    ports:
      - ${OLLAMA_PORT_HOST:-11434}:${OLLAMA_PORT:-11434}
    entrypoint: /app/entrypoint.sh

  comfyui-api:
    <<: *app-defaults
    container_name: comfyui-api
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    volumes:
      - ./workspace:${WORKSPACE:-/workspace/}
      - ./config/comfyui/provisioning.sh:/opt/ai-dock/bin/provisioning.sh
      - ./config/comfyui/models.csv:/opt/ai-dock/bin/models.csv
      - ./config/comfyui/nodes.csv:/opt/ai-dock/bin/nodes.csv
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
    ports:
      - ${COMFYUI_PORT_HOST:-8188}:${COMFYUI_PORT:-8188}
    environment:
      - COMFYUI_BRANCH=${COMFYUI_BRANCH:-master}
      - COMFYUI_FLAGS=${COMFYUI_FLAGS:-}
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
      - WORKSPACE=${WORKSPACE:-/workspace}
      - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH}
      - WEB_USER=${WEB_USER}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}
      - NODES_CSV_FILE=${NODES_CSV_FILE:-/opt/ai-dock/bin/nodes.csv}
      - MODELS_CSV_FILE=${MODELS_CSV_FILE:-/opt/ai-dock/bin/models.csv}

  ffmpeg:
    <<: *app-defaults
    container_name: ffmpeg-api
    image: craiggilchrist/ffmpeg-cuda:12.3
    command: tail -F keep_container_running
    volumes:
      - ./workspace/ffmpeg:/output
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount

networks:
  apinaio:
    name: apinaio
    driver: bridge